### ISSUE TITLE
Typescript compiler doesn't resolve index.ios.tsx / index.android.tsx

### ISSUE THREAD

**Issue by bherila** [molekilla/ReactNativeU2F#1]
Typescript is complaining that modules can't be found because they're named index.ios.tsx or index.android.tsx (as opposed to just index.tsx). Did anyone find a way around this problem?

e.g.
> src/app.component.tsx(10,25): error TS2307: Cannot find module './shared/components/loaders/progress-bar'.

Thanks,
Ben

**Comment by molekilla** [comment]
Hi,

This a playground type of project, not ready yet. Feel free to fix.

Thanks

**Comment by bherila** [comment]
Please reopen and I will send a PR @molekilla
